controller:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
  ingressClassResource:
    enabled: true
    name: nginx
    default: false
    annotations:
      kubernetes.io/ingress.class: nginx
  ingressClass: nginx
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ${env}.${dns_name}
