name: Docker Push
on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        run: |
          if [[ $GITHUB_REF == refs/heads/dev ]]; then
            echo "IMAGE_TAG=alpha" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "IMAGE_TAG=beta" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=no_build" >> $GITHUB_ENV
          fi

      - name: Build and Push
        if: env.IMAGE_TAG != 'no_build' && !startsWith(env.IMAGE_TAG, 'v')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: greyhats13/ols_auth:${{ env.IMAGE_TAG }}, greyhats13/ols_auth:${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8

      - name: Retag and Push for Release
        if: startsWith(env.IMAGE_TAG, 'v')
        run: |
          docker pull greyhats13/ols_auth:beta
          docker tag greyhats13/ols_auth:beta greyhats13/ols_auth:${{ env.IMAGE_TAG }}
          docker push greyhats13/ols_auth:${{ env.IMAGE_TAG }}