nodeSelector:
  iam.gke.io/gke-metadata-server-enabled: "true"

serviceAccount:
  name: "${unit}-${env}-${unit}-${feature}"
  annotations:
    iam.gke.io/gcp-service-account: "${service_account_annotation}"
