- name: Add HashiCorp GPG key
  become: yes
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
  tags:
    - install_terraform
    - add_hashicorp_gpg_key

- name: Get the Debian codename
  command: lsb_release -cs
  register: debian_codename
  changed_when: false
  tags: 
    - install_terraform
    - get_debian_codename

- name: Add HashiCorp repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ debian_codename.stdout }} main"
    state: present
  tags: 
    - install_terraform
    - add_hashicorp_repository

- name: Install Terraform
  become: yes
  apt:
    name: terraform
    state: present
  tags: 
    - install_terraform
    - install_terraform_apt
