serviceAccount:
  create: true
  name: "${service_account_name}"
  annotations:
    eks.amazonaws.com/role-arn: "${service_account_arn}"
    eks.amazonaws.com/sts-regional-endpoints: "true"
clusterName: "${extra_vars.cluster_name}"
disableIngressClassAnnotation: true
ingressClassConfig:
  default: true