global:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"

configs:
  secret:
    extra:
      dex.github.clientSecret: ${values_extra_vars.github_client_secret}
  cm:
    url: "https://${feature}.${dns_name}"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${values_extra_vars.github_client_id}
            clientSecret: $argocd-secret:dex.github.clientSecret
            redirectURI: 'https://${feature}.${dns_name}/api/dex/callback'
            orgs:
              - name: ${values_extra_vars.github_orgs}
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
    servicePortHttp: 80
    servicePortHttpName: http
  ingress:
    enabled: true
    hosts:
      - "${feature}.${dns_name}"
    annotations:
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      external-dns.alpha.kubernetes.io/hostname: "${feature}.${dns_name}"
      external-dns.alpha.kubernetes.io/ttl: "300"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-${unit}-${env}"
    ingressClassName: "nginx"
    tls:
      - secretName: "${unit}-${feature}-server-tls"
        hosts:
          - "${feature}.${dns_name}"
    # http: false