apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-${unit}-${env}
spec:
  acme:
    email: idanfreak@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-${unit}-${env}
    solvers:
    - http01:
        ingress:
          class: nginx