- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: present
  tags: 
    - install_atlantis
    - install_unzip

- name: Download Atlantis
  become: yes
  get_url:
    url: "https://github.com/runatlantis/atlantis/releases/download/v0.25.0/atlantis_linux_amd64.zip"
    dest: "/tmp/atlantis.zip"
    mode: "0755"
  tags: 
    - install_atlantis
    - download_atlantis

- name: Unzip Atlantis
  become: yes
  unarchive:
    src: "/tmp/atlantis.zip"
    dest: "/usr/local/bin"
    remote_src: yes
  tags: 
    - install_atlantis
    - unzip_atlantis

- name: Make Atlantis executable
  become: yes
  file:
    path: "/usr/local/bin/atlantis"
    mode: "0755"
  tags: 
    - install_atlantis
    - make_atlantis_executable
